# Generated by Django 2.2.4 on 2019-10-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegistartion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('DateofBirth', models.DateField()),
                ('BloodGroup', models.CharField(max_length=100)),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('ResidencyAddress', models.CharField(max_length=100)),
                ('MedicalHistory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technician_Name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('DateofBirth', models.DateField()),
                ('Age', models.IntegerField()),
                ('BloodGroup', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
    ]
