# Generated by Django 2.2.4 on 2019-11-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('Technician_id', models.IntegerField()),
                ('Patient_ID', models.IntegerField()),
                ('Patient_Name', models.CharField(max_length=100)),
                ('Test_Name', models.CharField(max_length=100)),
                ('Result', models.CharField(max_length=100)),
                ('Units', models.CharField(max_length=100)),
                ('Reference_range', models.CharField(max_length=100)),
                ('Doctor_Consulted', models.CharField(max_length=100)),
                ('Technician_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(max_length=100)),
                ('Result', models.CharField(max_length=100)),
                ('Units', models.CharField(max_length=100)),
                ('Reference_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CholestrolTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(max_length=100)),
                ('Result', models.CharField(max_length=100)),
                ('Units', models.CharField(max_length=100)),
                ('Reference_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(max_length=100)),
                ('Result', models.CharField(max_length=100)),
                ('Units', models.CharField(max_length=100)),
                ('Reference_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UricAcidTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(max_length=100)),
                ('Result', models.CharField(max_length=100)),
                ('Units', models.CharField(max_length=100)),
                ('Reference_range', models.CharField(max_length=100)),
            ],
        ),
    ]
