# Generated by Django 2.2.4 on 2019-11-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_remove_addtestresult_technician_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtest',
            name='Patient_ID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cholestroltest',
            name='Patient_ID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetestest',
            name='Patient_ID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uricacidtest',
            name='Patient_ID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
