# Generated by Django 2.2.4 on 2019-10-30 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabName', models.CharField(max_length=100)),
                ('DateTime', models.DateTimeField()),
                ('Patient_Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('Specimen_Collected', models.CharField(max_length=100)),
                ('Doctor_Consulted', models.CharField(max_length=100)),
                ('Test_Name', models.CharField(max_length=100)),
                ('Test', models.CharField(max_length=100)),
                ('Result', models.CharField(max_length=100)),
                ('Units', models.CharField(max_length=100)),
                ('Reference_range', models.CharField(max_length=100)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.PatientRegistartion')),
            ],
        ),
    ]
